name: clean workflow runs

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

permissions: write-all

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workflow runs
        uses: dongchengjie/workflow-runs-cleaner@v1
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          maintain-span: "1d"
